### PR TITLE
Throw Error instances instead of strings

### PR DESCRIPTION
**Pull request by marcbachmann**
Requested in issue #11
There are no tests against .get calls that would result in an error. Do you need some?

### CODE REVIEW

**Comment by marcbachmann** [comment]
Apparently node v0.4 isn't available anymore on travis. `nvm install 0.4` fails on there.

**Comment by janl** [comment]
perfect, thanks, sorry for the delay!

@marcbachmann fancy becoming a contributor here?

**Comment by marcbachmann** [comment]
No problem. I'm not in a hurry.
Yes, that's ok for me.

**Comment by janl** [comment]
cool, welcome aboard ;)

**Comment by marcbachmann** [comment]
@janl That change is still not published on npm. Can you add me there please. I currently can't publish.
Besides, this is a breaking API change, so I'll create a 2.0.0 release. If you let me :smile:

**Comment by janl** [comment]
@marcbachmann added you to the jsonpointer npm owners. Thanks! :)

**Pull request merged**
