### PR TITLE
chore: add semantic release

### PR DESCRIPTION
**Pull request by janl**

### CODE REVIEW

**Comment by marcbachmann** [comment]
What about package-lock file in this project?
Should we disable it using `echo "package-lock=false" > .npmrc`?

**Comment by janl** [comment]
I’d be ok with a lockfile, I wanted to add that next :)

Happy to disable it, if you prefer.

**Comment by marcbachmann** [comment]
There aren't many dependencies in here, so it doesn't really matter.
Adding it is fine.

**Comment by janl** [comment]
Aye

**Pull request merged**
