### PR TITLE
Add files entry to package.json.

### PR DESCRIPTION
**Pull request by jamestalmage**
Removes unnecessary files from the deployed package.

Deploying unnecessary files impacts the performance of `npm install` for everyone.

See: https://github.com/insin/package-config-checker

### CODE REVIEW

**Comment by marcbachmann** [comment]
Shouldn't we also include the license file?
Do you think the license definition in the package.json is enough?

**Comment by jamestalmage** [comment]
License files, and the Readme are included automatically (you can't disable, even if you wanted to).

**Comment by marcbachmann** [comment]
Ok. thanks.

**Comment by jvanharn** [comment]
Bump. @janl @marcbachmann 
Could this be merged? Minimal difference, but would still be hugely appreciated.

**Comment by marcbachmann** [comment]
Yes, I'll do a release soon.

**Comment by marcbachmann** [comment]
Done. Released as [4.0.1](https://www.npmjs.com/package/jsonpointer)

**Pull request merged**
